apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
  namespace: excercises
spec:
  storageClassName: ping-pong-storage
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi