apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingpong-volume
  namespace: excercises
spec:
  storageClassName: ping-pong-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0