apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: excercises
spec:
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: log-output-volume
        emptyDir: {}
      containers:
      - name: string-generator
        image: log-output-generator
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /data
            name: log-output-volume

      - name: string-server
        image: log-output-server
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /data
            name: log-output-volume
        env:
          - name: PORT
            value: "3000"