apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: excercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: ping-pong
        imagePullPolicy: Never
        env:
          - name: PORT
            value: "3000"
        envFrom:
          - configMapRef:
              name: postgres-config