apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: ping-pong
          persistentVolumeClaim:
            claimName: ping-pong-claim
            readOnly: false
      containers:
      - name: ping-pong
        image: ping-pong
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /ping-pong
            name: ping-pong
        env:
          - name: PORT
            value: "3000"