apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
      - name: image-cache
        emptyDir: {}
      containers:
      - name: todo-app
        image: todo-app
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "3000"
        - name: IMAGE_CACHE_DURATION
          value: "600000" # 10 minutes in milliseconds
        - name: PICTURE_SOURCE_URL
          value: "https://picsum.photos/1200/300.webp"
        volumeMounts:
        - name: image-cache
          mountPath: /image-cache