apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      volumes:
      - name: image-cache
        emptyDir: {}
      containers:
      - name: todo-app-backend
        image: todo-backend-image
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: postgres-config