apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: project
data:
  PG_DATABASE: "postgres"
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PG_USER: "postgres"
  PG_PASSWORD: "change-me"