apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app-backend
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3000