apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-job
  namespace: project
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wikipedia-fetcher
            image: alpine:latest
            command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache curl
              URL=$(curl -Ls -o /dev/null -w '%{url_effective}' 'https://en.wikipedia.org/wiki/Special:Random')
              echo "Fetched random article: $URL"
              curl -X POST -H "Content-Type: application/json" -d "{\"title\":\"read wikipedia\",\"content\":\"$URL\",\"color\":\"slategray\"}" http://todo-app-backend-svc:2345/api/todo
          restartPolicy: OnFailure